### ISSUE TITLE
Outputs in BIDS Derivatives Format

### ISSUE THREAD

**Issue by tjhendrickson** [ChildDevLab/MADE-EEG-preprocessing-pipeline#11]
Hello @SMoralesPhD  and all,

I was taking a look at the outputs from the MADE pipeline and noticed that despite being a BIDS-adjacent format (as you said they would be @SMoralesPhD) they are not quite BIDS.

Here is an example output from the pipeline:
sub-CENSORED_task-NonSocial_Flanker_run-01_eeg_processed_data.fdt
sub-CENSORED_task-NonSocial_Flanker_run-01_eeg_processed_data.set
sub-CENSORED_task-RestingState_and_NonSocial_Flanker_run-01_eeg_filtered_data.fdt
sub-CENSORED_task-RestingState_and_NonSocial_Flanker_run-01_eeg_filtered_data.set
sub-CENSORED_task-RestingState_and_NonSocial_Flanker_run-01_eeg_ica_data.fdt
sub-CENSORED_task-RestingState_and_NonSocial_Flanker_run-01_eeg_ica_data.set
sub-CENSORED_task-RestingState_run-01_eeg_processed_data.fdt
sub-CENSORED_task-RestingState_run-01_eeg_processed_data.set

Based on some of the [file naming conventions](https://bids-specification.readthedocs.io/en/stable/05-derivatives/01-introduction.html) suggested by BIDS it should be something like:
sub-CENSORED_task-NonSocialFlanker_run-01_eeg.fdt
sub-CENSORED_task-NonSocialFlanker_run-01_eeg.set
sub-CENSORED_task-RestingStateAndNonSocialFlanker_run-01_desc-filtered_eeg.fdt
sub-CENSORED_task-RestingStateAndNonSocialFlanker_run-01_desc-filtered_eeg_.set
sub-CENSORED_task-RestingStateAndNonSocialFlanker_run-01_desc-ica_eeg.fdt
sub-CENSORED_task-RestingStateAndNonSocialFlanker_run-01_desc-ica_eeg.set
sub-CENSORED_task-RestingState_run-01_desc-processed_eeg.fdt
sub-CENSORED_task-RestingState_run-01_desc-processed_eeg.set

@SMoralesPhD, Do you want to try making some of these modifications and report back to Eric and I how they went?

Best,

-Tim

**Comment by ChildDevLab** [comment]
Hi Tim,

Thank you for your feedback. I have made the requested changes to the naming conventions of the BIDS formatted files with in the pipeline. 

Best,
Lydia
