### ISSUE TITLE
Example interference Excel missing from GH

### ISSUE THREAD

**Issue by jessb0t** [ChildDevLab/MADE-EEG-preprocessing-pipeline#12]
Hello!

I recently read the MADE paper and noticed that it indicates, under Appendix A:
> An example excel file of interference trials can be found at https://github.com/ChildDevLab/MADE-EEG-preprocessing-pipeline.

It looks as though this file is not currently available on GitHub, so I wanted to bring it to your attention.

Sincerely,
Someone with an unhealthy love for Excel files :joy:

**Comment by ChildDevLab** [comment]
Hello,

We have added an excel file with an example of interference trials. Thank you for your patience!

Best,
Lydia
