### ISSUE TITLE
Problems Compiling MADE

### ISSUE THREAD

**Issue by tjhendrickson** [ChildDevLab/MADE-EEG-preprocessing-pipeline#13]
Hello,

I am attempting to compile MADE through the MATLAB compiler application and am experiencing an issue with some of the source code within EEGLab.

Here is the error:

**Error while determining required deployable files. Compilation terminated. Details:
Error using parseFile (line 13)
MATLAB code '/panfs/roc/groups/8/faird/shared/data/TOTS_UMD_collab/code/cdl-eeg-processing/MADE-EEG-preprocessing-pipeline/eeglab2021.0/plugins/clean_rawdata/manopt/tests/Test_fixedrank_tensor.m' contains the following syntax error(s):
Line 297 column 9 : The current use of 'cost' is inconsistent with its previous use or definition (line 85).
mcc failed.**

Any ideas?

**Comment by ChildDevLab** [comment]
Hello,

We haven't encountered this specific error before, but the EEGLab plugin that seems to be causing your error is not used anywhere in the MADE pipeline, so you could try removing the clean_rawdata plugin from your path and see if that helps.

Best,
Lydia

**Comment by tjhendrickson** [comment]
Yes, I actually simultaneously reached out to EEGLab and they suggested I remove the "manopts" folder. It resolved my issue.

Thanks!
