### ISSUE TITLE
Occular Electrodes and Outer Ring Electrodes for EGI HCGSN 128

### ISSUE THREAD

**Issue by trollerrenfr** [ChildDevLab/MADE-EEG-preprocessing-pipeline#6]
Hi MADE Team!

Thanks again for your wonderful pipeline.  I was just reviewing the accompanying manuscript and I was curious about the electrode numbers you removed for Epoch-Level Occular Voltage Threshold Rejection and outer ring.

Could you tell me what electrode numbers/names were removed for each step for the 128 Hydrocel caps from EGI?

Thanks!
Sonya

**Comment by StephLeach** [comment]
Hello Sonya,

Thank you for bringing this to our attention. For a 128 channel Hydocel cap from EGI we use {'E1', 'E8', 'E14', 'E21', 'E25', 'E32', 'E17'} for epoch-level ocular voltage threshold rejection and we consider {'E17' 'E38' 'E43' 'E44' 'E48' 'E49' 'E113' 'E114' 'E119' 'E120' 'E121' 'E125' 'E126' 'E127' 'E128' 'E56' 'E63' 'E68' 'E73' 'E81' 'E88' 'E94' 'E99' 'E107'} to be part of the outer ring, which we remove.

Also, we have added these recommended channel lists (in the form of a comment) to the MADE preprocessing script.

Thanks,
Steph
