### ISSUE TITLE
step 11 - thresholding V or mV?

### ISSUE THREAD

**Issue by KZacharaki** [ChildDevLab/MADE-EEG-preprocessing-pipeline#8]
Hi! I have been using the pipeline to preprocess some infant data. I was wondering whether the threshold value in step 11 should be in volts or microvolts. When I downloaded the script there was a question mark before the V inside the parenthesis (lower and upper threshold in ?V). It could be due to a special character like μ but I wanted to make sure since my data look quite noisy after preprocessing. What threshold would you suggest?
Thank you!

**Comment by StephLeach** [comment]
Hi KZacharaki,

Yes, the threshold value in step 11 should be in microvolts. You are correct that the ? is the result of a special character. We've now changed the comment in the script to say "mV" to hopefully make this clearer. Thank you for pointing this issue out to us!

With adult data, we typically use -/+125 microvolts (but -/+100 is another common choice). For children we typically use -/+150 microvolts. We usually use -/+150 microvolts with infants, but you could probably use -/+200 microvolts as long as you visually inspect the files after preprocessing and make sure it's still doing a good job at removing ocular artifacts and/or drifty portions of data.

-Steph

**Comment by KZacharaki** [comment]
Thank you for the quick reply! This is very helpful :)

**Comment by KZacharaki** [comment]
Hi again!
We have tried to do the artifact rejection and we get the error: 
'eeg_checkset warning: 362/570 events had out-of-bounds latencies and were removed
Event resorted by increasing latencies.'
However, we don't get the same error when we increase the threshold. Do you have any thoughts on this?
Thank you in advance,
Konstantina

**Comment by StephLeach** [comment]
Hi Konstantina,

Thank you for reaching out about this issue. Can you give us a few more pieces of information to help us with troubleshooting?

-What system did you use to collect your data and what format is the raw data in?
     -related to this, is the recording continuous or did you start and stop recording at the start and end of each trial?
-What was the original threshold and what did you change it to?
-What is your epoch length?
-When you got the eeg_checkset warning, what did your data look like immediately before and after getting this warning?
     - related to this, where exactly in the code do you get this eeg_checkset warning (i.e., after running which exact line of code does this warning occur)?

Thanks,
Steph

**Comment by EgeEkinOzer** [comment]
Hi Steph, I am working with Konstantina on this. Let me address your questions.

-What system did you use to collect your data and what format is the raw data in?
 "EEG data were collected using a 64-electrode geodesicsensor-net (Electrical Geodesic, Inc. system) referenced to the vertex. The EEG was digitalized at 500 Hz."
The data were collected around 2003, according to what we see on Matlab.

-related to this, is the recording continuous or did you start and stop recording at the start and end of each trial?
The recording was continuous but  "The experiment was stopped for less than 60 seconds for only four infants"

-What was the original threshold and what did you change it to?
We started with [-130 +130] according to the methodology in the original experiment.
When we use volt_threshold = [-130 130]; % lower and upper threshold (in ?V), these are the warnings we get for pop_eegthresh at line 735:
48 channel selected
966/967 trials marked for rejection

These lines lead us to fall into the if loop in Line 741 and we end up getting:
            warning(['No usable data for datafile', datafile_names{subject}]);

When we change the threshold limits and use [-200 200]  just to try,
volt_threshold = [-200 200]; % lower and upper threshold (in ?V)
These are the warnings we get:
905/967 trials marked for rejection

Using this threshold, we do not fall into the if statement in the 741, but follow to the else statement in the same loop on 751, then until line 753:
905/967 trials rejected
Removing 905 trial(s)...
Pop_select: removing 3149 unreferenced events
eeg_checkset warning: 62/309 events had out-of-bounds latencies and were removed


-What is your epoch length?
3800 ms [-800 3000] 


-When you got the eeg_checkset warning, what did your data look like immediately before and after getting this warning?
Attached are some screenshots of the EEG fields before and after line 735 (to answer your following question)
As you can see, nothing (that we can see) changes in the EEG. But we still get the warnings.
![before735](https://user-images.githubusercontent.com/60706983/119972705-d1ceb180-bfb2-11eb-90d7-504b19094d1b.jpg)
![after735](https://user-images.githubusercontent.com/60706983/119972708-d2674800-bfb2-11eb-843b-7efb3ea25c20.jpg)
